#!/bin/bash

src_path=$(dirname "$(realpath $0)")/..

cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_VERBOSE_MAKEFILE=OFF \
    -DUSE_ROC_SHMEM=OFF \
    -DUSE_HIP=ON \
    -DALL_ANALYZE=ON \
    -DUSE_DOUBLE=OFF \
    -DALL_LEVELSET=OFF \
    -DALL_LEVELSYNC=OFF \
    -DALL_SYNCFREE=OFF \
    $src_path
cmake --build . --parallel 8
